[RPC] Add REST RPCType detection and error reply formatting
pokt-network/shannon-sdk pull request #4
Opened 2024-06-07 02:59 UTC by red-0ne

# Summary:
This PR introduces support for `RPCType` detection for `REST` requests and adds a helper function for error reply formatting.

# Details:
This update replaces the partials package in the `poktroll` repository, making its functionality available to any consumer of the SDK.

## New Features:

1. `GetRPCType` Function:

* Detects `JSON-RPC` and `REST` requests.
* Accepts a `POKTHTTPRequest` and returns the corresponding `poktroll`'s `sharedtypes.RPCType`.

2. `FormatError` Helper Function:

Accepts an error, the original `POKTHTTPRequest`, and `RPCType`.
Returns a `POKTHTTPResponse` representing the error, formatted according to the `RPCType` and refined using the `POKTHTTPRequest`.

## Improvements:

Refactors the `POKTHTTPRequest/Response` codecs to return intermediary steps, reducing redundant (de)serializations by the SDK consumer.

This PR partially addresses ticket https://github.com/pokt-network/poktroll/issues/221

2024-06-11 00:50 UTC, Olshansk requested changes
@red-0ne Great start!

Left a handful of comments that will likely be repeated, so stopping my review about halfway and will redo the review again afterwards.

2024-06-11 00:50 UTC, Olshansk commented on rpcdetect/jsonrpc.go
> +	if !slices.Contains(contentType.Values, "application/json") {
Move `applicaiton/json` into a local constant and reuse.

2024-06-11 00:50 UTC, Olshansk commented on rpcdetect/jsonrpc.go
> +// jsonRPCPayload represents the JSON-RPC payload fields that are relevant for
Are we just using this for detection or more?

1. If it's purely for detection -> ename to `jsonRPCPayloadMeta`
2. If it's for more -> #PUC

Ditto elsewhere.

2024-06-11 00:50 UTC, Olshansk commented on rpcdetect/rest.go
> +func isREST(poktRequest *types.POKTHTTPRequest) bool {
I feel like almost all the functions take a req as a param field.

Given that goland has receivers and an "object oriented approach", it's more appropriate than going down this function path.

2024-06-11 00:50 UTC, Olshansk commented on rpcdetect/jsonrpc.go
> +			"code":    -32000,
Keep seeing this number everywhere

2024-06-11 00:50 UTC, Olshansk commented on rpcdetect/jsonrpc.go
> +		Values: []string{"application/json"},
Move to a constant?

2024-06-12 10:54 UTC, red-0ne commented on rpcdetect/rpc_id.go
> +package rpcdetect
Moved the whole package to `types` in order to have `isXXX` and `FormaError` as receivers.

2024-06-12 11:20 UTC, red-0ne commented on rpcdetect/jsonrpc.go
> +	Id      uint64 `json:"id"`
Yes, struct with json tag want to be exported.
![image](https://github.com/pokt-network/shannon-sdk/assets/231488/a8755abc-41a1-469f-8384-d0c48073e6cb)

2024-06-12 20:46 UTC, Olshansk approved these changes
Couple minor NITs but nothing blocking!

2024-06-12 20:46 UTC, Olshansk commented on types/jsonrpc.go
> +// init initializes the package level variables for the JSON-RPC error reply.
```suggestion
// init initializes the package level variables such as the JSON-RPC error reply.
```

2024-06-12 20:46 UTC, Olshansk commented on types/rest.go
> +// init initializes the package level variables for the REST error reply.
```suggestion
// init initializes the package level variables such as the REST error reply.
```

2024-06-12 20:46 UTC, Olshansk commented on types/rpc_id.go
> +// init initializes the package level variables for the unsupported RPC type error reply.
```suggestion
// init initializes the package level variables such as unsupported RPC type error reply.
```

2024-06-12 20:46 UTC, Olshansk commented on types/rpc_id.go
> +package types
Thoughts on renaming this file to `rpc_helpers`, `rpc_default` or `rpc_errors`?

Probably the last one is best.

2024-06-13 00:53 UTC, merged